plugins {
    id 'java'
    id 'io.github.goooler.shadow' version '8.1.8'
}

group = 'com.sound2disc'
version = '1.0.0'

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

repositories {
    mavenCentral()
    maven { url 'https://repo.papermc.io/repository/maven-public/' }
}

dependencies {
    compileOnly 'io.papermc.paper:paper-api:1.20.4-R0.1-SNAPSHOT'
}

shadowJar {
    archiveClassifier.set('')
}

build.dependsOn shadowJar
